### ISSUE TITLE
Error with Athena-Cyber-Hub and Cinnamon DE

### ISSUE THREAD

**Issue by hammy283** [Athena-OS/athena-cyber-hub#1]
Hi,

So I installed Cinnamon DE using the Rust programming installer from the iso. I tried to start the athena-cyber-hub but I get this error:

Traceback (most recent call last):
  File "/usr/bin/athena-cyber-hub", line 46, in <module>
    from athena_cyber_hub import main
  File "/usr/share/athena-cyber-hub/athena_cyber_hub/main.py", line 33, in <module>
    from .window import AthenaWindow
  File "/usr/share/athena-cyber-hub/athena_cyber_hub/window.py", line 29, in <module>
    from athena_cyber_hub.backends.ach import Ach
  File "/usr/share/athena-cyber-hub/athena_cyber_hub/backends/ach.py", line 35, in <module>
    class Ach:
  File "/usr/share/athena-cyber-hub/athena_cyber_hub/backends/ach.py", line 55, in Ach
    data = toml.load("/usr/share/athena-cyber-hub/vulhub/environments.toml")
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.11/site-packages/toml/decoder.py", line 134, in load
    return loads(ffile.read(), _dict, decoder)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.11/site-packages/toml/decoder.py", line 340, in loads
    raise TomlDecodeError("Unbalanced quotes", original, i)
toml.decoder.TomlDecodeError: Unbalanced quotes (line 567 column 23 char 13104)

How do I fix it?

Thanks,
hammy

**Comment by D3vil0p3r** [comment]
Fixed https://github.com/vulhub/vulhub/pull/473
